[2025-04-06 04:00:14][MAIN] - Bot is ready.
[2025-04-06 04:00:14][MAIN] - Pulling from GitHub: /home/claudio/Python-Projects/RoomServer
[2025-04-06 04:00:15][MAIN] - Contacting Arduino..
[2025-04-06 04:00:15][MAIN] - Already up to date.
[2025-04-06 04:00:20][MAIN] - IP 84.155.67.199 uploaded to:
[2025-04-06 04:00:20][MAIN] - https://storage.googleapis.com/ip-manager42.appspot.com/RaspberryPi-Cyan/ip_server.txt
[2025-04-06 04:00:20][FLASK] -  * Serving Flask app 'server'
[2025-04-06 04:00:20][FLASK] -  * Debug mode: off
[2025-04-06 04:00:20][FLASK] - Address already in use
[2025-04-06 04:00:20][FLASK] - Port 10004 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-04-06 04:00:20][WEBSOCKET] -  * Serving Flask app 'websocket_server'
[2025-04-06 04:00:20][WEBSOCKET] -  * Debug mode: off
[2025-04-06 04:00:20][WEBSOCKET] - Address already in use
[2025-04-06 04:00:20][WEBSOCKET] - Port 10003 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-04-06 10:17:54][MAIN] - Traceback (most recent call last):
[2025-04-06 10:17:54][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 89, in <module>
[2025-04-06 10:17:54][MAIN] - main()
[2025-04-06 10:17:54][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 77, in main
[2025-04-06 10:17:54][MAIN] - time.sleep(0.5)
[2025-04-06 10:17:54][MAIN] - KeyboardInterrupt
[2025-04-06 10:17:55][MAIN] - Exception ignored in: 
[2025-04-06 10:17:55][MAIN] - <module 'threading' from '/usr/lib/python3.10/threading.py'>
[2025-04-06 10:17:55][MAIN] - Traceback (most recent call last):
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
[2025-04-06 10:17:55][MAIN] - lock.acquire()
[2025-04-06 10:17:55][MAIN] - KeyboardInterrupt
[2025-04-06 10:17:55][MAIN] - : 
[2025-04-06 10:17:55][MAIN] - Exception ignored in atexit callback
[2025-04-06 10:17:55][MAIN] - : 
[2025-04-06 10:17:55][MAIN] - <function _exit_function at 0x7f277df6f490>
[2025-04-06 10:17:55][MAIN] - Traceback (most recent call last):
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/multiprocessing/util.py", line 334, in _exit_function
[2025-04-06 10:17:55][MAIN] - _run_finalizers(0)
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/multiprocessing/util.py", line 300, in _run_finalizers
[2025-04-06 10:17:55][MAIN] - finalizer()
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/multiprocessing/util.py", line 224, in __call__
[2025-04-06 10:17:55][MAIN] - res = self._callback(*self._args, **self._kwargs)
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/multiprocessing/managers.py", line 674, in _finalize_manager
[2025-04-06 10:17:55][MAIN] - process.join(timeout=1.0)
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/multiprocessing/process.py", line 149, in join
[2025-04-06 10:17:55][MAIN] - res = self._popen.wait(timeout)
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 40, in wait
[2025-04-06 10:17:55][MAIN] - if not wait([self.sentinel], timeout):
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/multiprocessing/connection.py", line 931, in wait
[2025-04-06 10:17:55][MAIN] - ready = selector.select(timeout)
[2025-04-06 10:17:55][MAIN] -   File "/usr/lib/python3.10/selectors.py", line 416, in select
[2025-04-06 10:17:55][MAIN] - fd_event_list = self._selector.poll(timeout)
[2025-04-06 10:17:55][MAIN] - KeyboardInterrupt
[2025-04-06 10:17:55][MAIN] - : 
