[2025-02-08 18:43:29][MAIN] - Contacting Arduino..
[2025-02-08 18:43:29][MAIN] - Arduino found!
[2025-02-08 18:43:29][MAIN] - Actuator running.
[2025-02-08 18:43:29][MAIN] - Pulling from GitHub: /home/claudio/Python-Projects/RoomServer
[2025-02-08 18:43:31][MAIN] - Already up to date.
[2025-02-08 18:43:31][MAIN] - To Arduino: LIGHTSON
[2025-02-08 18:43:34][MAIN] - IP 84.150.103.227 uploaded to:
[2025-02-08 18:43:34][MAIN] - https://storage.googleapis.com/ip-manager42.appspot.com/RaspberryPi-Cyan/ip_server.txt
[2025-02-08 18:43:34][FLASK] -  * Serving Flask app 'server'
[2025-02-08 18:43:34][FLASK] -  * Debug mode: off
[2025-02-08 18:43:34][FLASK] - Process Process-2:
[2025-02-08 18:43:34][FLASK] - Traceback (most recent call last):
[2025-02-08 18:43:34][FLASK] -   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap

[2025-02-08 18:43:34][FLASK] -     self.run()
[2025-02-08 18:43:34][FLASK] -   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run

[2025-02-08 18:43:34][FLASK] -     self._target(*self._args, **self._kwargs)
[2025-02-08 18:43:34][FLASK] -   File "/home/claudio/Python-Projects/RoomServer/server.py", line 48, in start_flask_server

[2025-02-08 18:43:34][FLASK] -     app.run(host='0.0.0.0', port=HOSTNAME['server_port'], allow_unsafe_werkzeug=True)
[2025-02-08 18:43:34][FLASK] -   File "/home/claudio/Python-Projects/RoomServer/.venv/lib/python3.10/site-packages/flask/app.py", line 662, in run

[2025-02-08 18:43:34][FLASK] -     run_simple(t.cast(str, host), port, self, **options)
[2025-02-08 18:43:34][FLASK] - TypeError: run_simple() got an unexpected keyword argument 'allow_unsafe_werkzeug'
[2025-02-08 18:43:34][WEBSOCKET] -  * Serving Flask app 'websocket'
[2025-02-08 18:43:34][WEBSOCKET] -  * Debug mode: off
[2025-02-08 18:44:51][MAIN] - Traceback (most recent call last):
[2025-02-08 18:44:51][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 89, in <module>
[2025-02-08 18:44:51][MAIN] - main()
[2025-02-08 18:44:51][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 77, in main
[2025-02-08 18:44:51][MAIN] - time.sleep(0.5)
[2025-02-08 18:44:51][MAIN] - KeyboardInterrupt
[2025-02-08 18:44:51][MAIN] - Exception ignored in: 
[2025-02-08 18:44:51][MAIN] - <module 'threading' from '/usr/lib/python3.10/threading.py'>
[2025-02-08 18:44:51][MAIN] - Traceback (most recent call last):
[2025-02-08 18:44:51][MAIN] -   File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
[2025-02-08 18:44:51][MAIN] - lock.acquire()
[2025-02-08 18:44:51][MAIN] - KeyboardInterrupt
[2025-02-08 18:44:51][MAIN] - : 
