[2025-04-07 04:00:29][MAIN] - Bot is ready.
[2025-04-07 04:00:29][MAIN] - Pulling from GitHub: /home/claudio/Python-Projects/RoomServer
[2025-04-07 04:00:30][MAIN] - Contacting Arduino..
[2025-04-07 04:00:31][MAIN] - Already up to date.
[2025-04-07 04:00:35][MAIN] - IP 84.155.67.199 uploaded to:
[2025-04-07 04:00:35][MAIN] - https://storage.googleapis.com/ip-manager42.appspot.com/RaspberryPi-Cyan/ip_server.txt
[2025-04-07 04:00:35][FLASK] -  * Serving Flask app 'server'
[2025-04-07 04:00:35][FLASK] -  * Debug mode: off
[2025-04-07 04:00:35][FLASK] - Address already in use
[2025-04-07 04:00:35][FLASK] - Port 10004 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-04-07 04:00:35][WEBSOCKET] -  * Serving Flask app 'websocket_server'
[2025-04-07 04:00:35][WEBSOCKET] -  * Debug mode: off
[2025-04-07 04:00:35][WEBSOCKET] - Address already in use
[2025-04-07 04:00:35][WEBSOCKET] - Port 10003 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-04-07 08:00:00][MAIN] - ANNOUNCEMENTS
[2025-04-07 08:00:00][MAIN] - 2025-04-07 08:00:00.515226
[2025-04-07 08:00:02][MAIN] - Pulling from GitHub: /home/claudio/Python-Projects/RoomServer
[2025-04-07 08:00:03][MAIN] - Already up to date.
[2025-04-07 08:00:05][MAIN] - History updated.
[2025-04-07 08:00:05][MAIN] -           Week      Cesare     Claudio  ...         Lea        Mara    Natchaya
[2025-04-07 08:00:05][MAIN] - [96m44  2024-12-09  Management    Vacation  ...    Vacation   Bathrooms       Floor[0m
[2025-04-07 08:00:05][MAIN] - [96m45  2024-12-16     Anarchy     Anarchy  ...     Anarchy     Anarchy     Anarchy[0m
[2025-04-07 08:00:05][MAIN] - [96m46  2024-12-23     Anarchy     Anarchy  ...     Anarchy     Anarchy     Anarchy[0m
[2025-04-07 08:00:05][MAIN] - [96m47  2024-12-30   Bathrooms    Vacation  ...    Vacation     Kitchen  Management[0m
[2025-04-07 08:00:05][MAIN] - [96m48  2025-01-06    Vacation   Bathrooms  ...  Management       Floor     Kitchen[0m
[2025-04-07 08:00:05][MAIN] - [96m49  2025-01-13       Floor       Blame  ...   Bathrooms    Vacation    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [96m50  2025-01-20    Vacation       Floor  ...     Kitchen  Management   Bathrooms[0m
[2025-04-07 08:00:05][MAIN] - [96m51  2025-01-27     Kitchen  Management  ...       Floor    Vacation    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [96m52  2025-02-03    Vacation     Kitchen  ...    Vacation   Bathrooms  Management[0m
[2025-04-07 08:00:05][MAIN] - [96m53  2025-02-10       Floor   Bathrooms  ...  Management     Kitchen    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [96m54  2025-02-17  Management    Vacation  ...   Bathrooms    Vacation       Floor[0m
[2025-04-07 08:00:05][MAIN] - [96m55  2025-02-24    Vacation  Management  ...    Vacation       Floor     Kitchen[0m
[2025-04-07 08:00:05][MAIN] - [96m56  2025-03-03   Bathrooms       Floor  ...     Kitchen  Management    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [96m57  2025-03-10       Floor     Kitchen  ...    Vacation    Vacation   Bathrooms[0m
[2025-04-07 08:00:05][MAIN] - [96m58  2025-03-17    Vacation    Vacation  ...       Floor   Bathrooms  Management[0m
[2025-04-07 08:00:05][MAIN] - [96m59  2025-03-24     Kitchen   Bathrooms  ...  Management       Floor    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [38;5;208m60  2025-03-31   Bathrooms  Management  ...    Vacation    Vacation     Kitchen[0m
[2025-04-07 08:00:05][MAIN] - [91m61  2025-04-07    Vacation    Vacation  ...   Bathrooms     Kitchen       Floor[0m
[2025-04-07 08:00:05][MAIN] - [91m62  2025-04-14  Management       Floor  ...     Kitchen   Bathrooms    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [91m63  2025-04-21       Floor     Kitchen  ...    Vacation    Vacation  Management[0m
[2025-04-07 08:00:05][MAIN] - [91m64  2025-04-28    Vacation    Vacation  ...       Floor  Management   Bathrooms[0m
[2025-04-07 08:00:05][MAIN] - [91m65  2025-05-05     Kitchen   Bathrooms  ...  Management       Floor    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [91m66  2025-05-12   Bathrooms  Management  ...    Vacation    Vacation     Kitchen[0m
[2025-04-07 08:00:05][MAIN] - [91m67  2025-05-19    Vacation    Vacation  ...   Bathrooms     Kitchen       Floor[0m
[2025-04-07 08:00:05][MAIN] - [91m68  2025-05-26  Management       Floor  ...     Kitchen   Bathrooms    Vacation[0m
[2025-04-07 08:00:05][MAIN] - [91m69  2025-06-02       Floor     Kitchen  ...    Vacation    Vacation  Management[0m
[2025-04-07 08:00:05][MAIN] - [91m70  2025-06-09    Vacation    Vacation  ...       Floor  Management   Bathrooms[0m
[2025-04-07 08:00:05][MAIN] - list index out of range
[2025-04-07 08:00:05][MAIN] - Traceback (most recent call last):

[2025-04-07 08:00:05][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/announcements.py", line 1120, in set_announcement

[2025-04-07 08:00:05][MAIN] -     text, week_schedule = bac.generate_plan()

[2025-04-07 08:00:05][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/wg/bac.py", line 412, in generate_plan

[2025-04-07 08:00:05][MAIN] -     save_plan(wg_members, current_date, start_end_dates)

[2025-04-07 08:00:05][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/wg/bac.py", line 227, in save_plan

[2025-04-07 08:00:05][MAIN] -     print_df(reduced_df, current_date)

[2025-04-07 08:00:05][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/wg/bac.py", line 210, in print_df

[2025-04-07 08:00:05][MAIN] -     date_str = line.split()[1]

[2025-04-07 08:00:05][MAIN] - IndexError: list index out of range
[2025-04-07 19:40:23][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:40:23][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3318582950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:40:31][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:40:31][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f331aeff8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:40:39][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:40:39][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f331af6bf10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:40:57][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:40:57][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f331af69c90>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:41:05][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:41:05][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3318582290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:41:13][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:41:13][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f331aefe950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:41:21][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:41:21][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f331af69000>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:41:29][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:41:29][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3318583280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:41:37][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:41:37][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f331aeff8e0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
[2025-04-07 19:42:03][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:42:03][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318581390>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:42:28][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:42:28][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318424040>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:42:53][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:42:53][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f331aeffe50>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:43:18][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:43:18][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f331af6a0e0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:43:43][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:43:43][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318426140>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:43:58][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:43:58][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318583580>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:44:13][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:44:13][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f33182780a0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:44:28][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:44:28][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f331844b730>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:44:43][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:44:43][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f33184498a0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:44:58][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:44:58][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f331844ba90>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:45:13][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:45:13][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318449f30>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:45:28][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:45:28][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318449bd0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:45:43][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:45:43][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318449cf0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:45:58][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:45:58][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318427040>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:46:13][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:46:13][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f33184499c0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:46:28][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:46:28][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f33184274f0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:46:43][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:46:43][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f3318449960>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:46:59][MAIN] - Issue while trying to upload IP (initialization)
[2025-04-07 19:46:59][MAIN] - HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f331af6acb0>: Failed to resolve 'api.ipify.org' ([Errno -3] Temporary failure in name resolution)"))
[2025-04-07 19:47:05][MAIN] - IP 84.155.70.84 uploaded to:
[2025-04-07 19:47:05][MAIN] - https://storage.googleapis.com/ip-manager42.appspot.com/RaspberryPi-Cyan/ip_server.txt
[2025-04-07 19:47:06][WEBSOCKET] -  * Serving Flask app 'websocket_server'
[2025-04-07 19:47:06][WEBSOCKET] -  * Debug mode: off
[2025-04-07 19:47:06][WEBSOCKET] - Address already in use
[2025-04-07 19:47:06][WEBSOCKET] - Port 10003 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-04-07 19:47:06][FLASK] -  * Serving Flask app 'server'
[2025-04-07 19:47:06][FLASK] -  * Debug mode: off
[2025-04-07 19:47:06][FLASK] - Address already in use
[2025-04-07 19:47:06][FLASK] - Port 10004 is in use by another program. Either identify and stop that program, or start the server with a different port.
[2025-04-08 04:00:00][MAIN] - Arduino found!
[2025-04-08 04:00:00][MAIN] - Actuator running.
[2025-04-08 04:00:00][MAIN] - Actuators killed.
[2025-04-08 04:00:00][MAIN] - Flask server killed
[2025-04-08 04:00:00][MAIN] - Server control terminated.
[2025-04-08 04:00:00][MAIN] - Websocket killed
[2025-04-08 04:00:00][MAIN] - Websocket control terminated.
[2025-04-08 04:00:00][MAIN] - Firebase task terminated.
[2025-04-08 04:00:07][MAIN] - Bot killed.
[2025-04-08 04:00:07][MAIN] - RESTART
