[2025-02-08 20:04:55][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:04:56][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:04:57][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:04:58][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:04:59][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:05:00][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:05:01][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:05:01][MAIN] - IP 84.150.103.227 uploaded to:
[2025-02-08 20:05:01][MAIN] - https://storage.googleapis.com/ip-manager42.appspot.com/RaspberryPi-Cyan/ip_server.txt
[2025-02-08 20:05:02][FLASK] -  * Serving Flask app 'server'
[2025-02-08 20:05:02][FLASK] -  * Debug mode: off
[2025-02-08 20:05:02][WEBSOCKET] -  * Serving Flask app 'websocket'
[2025-02-08 20:05:02][WEBSOCKET] -  * Debug mode: off
[2025-02-08 20:05:02][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:05:03][MAIN] - Traceback (most recent call last):
[2025-02-08 20:05:03][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 89, in <module>
[2025-02-08 20:05:03][MAIN] - main()
[2025-02-08 20:05:03][MAIN] -   File "/home/claudio/Python-Projects/RoomServer/main.py", line 77, in main
[2025-02-08 20:05:03][MAIN] - time.sleep(0.5)
[2025-02-08 20:05:03][MAIN] - KeyboardInterrupt
[2025-02-08 20:05:03][MAIN] - Cannot open port /dev/ttyUSB0
[2025-02-08 20:05:04][MAIN] - Exception ignored in: 
[2025-02-08 20:05:04][MAIN] - <module 'threading' from '/usr/lib/python3.10/threading.py'>
[2025-02-08 20:05:04][MAIN] - Traceback (most recent call last):
[2025-02-08 20:05:04][MAIN] -   File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
[2025-02-08 20:05:04][MAIN] - lock.acquire()
[2025-02-08 20:05:04][MAIN] - KeyboardInterrupt
[2025-02-08 20:05:04][MAIN] - : 
